name: Build and Push Docker image

on:
  push:
    branches:
      - vue-next

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Load .env file
        run: |
          set -a
          . ./.env.production
          set +a
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Log in to Alibaba Cloud Container Registry
        uses: docker/login-action@v1
        with:
          registry: crpi-gjiqcc10v58u83a9.cn-hangzhou.personal.cr.aliyuncs.com
          username: ${{ secrets.ALIYUN_USERNAME }}
          password: ${{ secrets.ALIYUN_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: crpi-gjiqcc10v58u83a9.cn-hangzhou.personal.cr.aliyuncs.com/qtcms/qt-cms-vue:${{ env.VERSION }}
